### ISSUE TITLE
book

### ISSUE THREAD

**Issue by theja-vanka** [PacktPublishing/Deep-Learning-with-PyTorch-Lightning#4]
Hi, I have recently purchased your book for 3300/- along with shipping cost. There are a lot of code mistakes such as indentation and trying to reproduce code is a hassle. Very disappointed.

**Comment by theja-vanka** [comment]
Wow really. Very disappointed. Note to self, this is going on linkedin.

**Comment by Borda** [comment]
@theja-vanka can you five some specific examples? so we can try to do something about it... :confused:

**Comment by kunal-savvy** [comment]
@theja-vanka The book is not yet released and neither is available for shipping, how did you got it? . Can you provide proof of purchase? And also be specific abt what are the errors you are talking abt? Otherwise, this considered as trolling.

**Comment by theja-vanka** [comment]
![IMG_20220305_134520](https://user-images.githubusercontent.com/22734103/157072453-f66e2d40-ae66-4ef5-b277-3d8eb96c5644.jpeg)
![IMG_20220305_134502](https://user-images.githubusercontent.com/22734103/157072581-e15c26a6-66b9-4847-b26e-ca4a622a4155.jpeg)
![IMG_20220305_134428](https://user-images.githubusercontent.com/22734103/157072744-9d9722c6-8e93-4942-834b-0703db7f5816.jpeg)

**Comment by theja-vanka** [comment]
![screenshot_2022-03-05_at_4 10 10_pm](https://user-images.githubusercontent.com/22734103/157072910-54009e53-88e6-4afc-aa14-ea2bad432776.png)

Is this proof enough ?? Or do you need more screenshots ?

**Comment by theja-vanka** [comment]
@kunal-savvy Its been 3 days and I haven't heard from you. What's the verdict ?

**Comment by kunal-savvy** [comment]
@theja-vanka I am sorry for inconvenience . I have asked publisher to look into this one as to what exactly happened in this case.  I was not aware of shipping of this version of the book. We were working on upgrading all code to latest version to take care of most of changes to PL framework after 1.5.x and that is meant to be wider official release. I will personally  ensure that a revised version copy (officially released copy) where we have upgraded most of the chapters to PyTorch Lightning 1.5.x is sent to you free of cost. It should start shipping in couple of weeks.

**Comment by theja-vanka** [comment]
Thank you very much. Really appreciate it. Looking forward to a good experience from your new book.
