### ISSUE TITLE
Chap 2: Transport endpoint is not connected: '/content/gdrive'

### ISSUE THREAD

**Issue by suredream** [PacktPublishing/Deep-Learning-with-PyTorch-Lightning#8]
No luck to run the following cell, no matter I mount google drive as /content/gdrive  or /content/drive, same error information came out. Any idea?
![image](https://user-images.githubusercontent.com/1661077/175756633-406e8162-025c-45a9-b2a8-5fcaa81d5a55.png)

**Comment by kunal-savvy** [comment]
What do you see after mounting ? 

Can you do ls ?

**Comment by Shivam6693** [comment]
Hi @suredream,

Please try one of these steps to get past this error:

1. Unmount and mount the drive again:
```
!fusermount -u drive
!google-drive-ocamlfuse drive
```

2. Go to Runtime on menubar and click on restart runtime option.
Or simply use the shortcut press CTRL + M

3. Terminate the session by going to : Runtime -> Manage Sessions, then Click on terminate for the session. Then you can re-mount the drive.

4. Use the argument force_remount = True like this 
```
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
```

5. Try to factory reset the runtime.

Using any one of this step, you should be able to mount the drive on Google Colab notebook.

**Comment by kunal-savvy** [comment]
@suredream did it work ?

**Comment by kunal-savvy** [comment]
Closing this as no further response received . Feel free to comment on this if any further help needed
